customhost = "employee.clz3bu9hdkmh.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "leechongzuan-employee"
customregion = "us-east-1"
